spring:
  datasource:
    url: jdbc:mysql://root:B6gA3ea-1G2cf1AbDF6GbghFAF-5gbdF@mysql.internal:3306/railway
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: railway

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes

