CREATE TABLE registro (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  descripcion VARCHAR(255) NOT NULL
);

-- Inserts de prueba
INSERT INTO registro (nombre, descripcion) VALUES ('36 CRAZYFISTS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('7 ANGELS 7 PLAGUES', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('A DAY TO REMEMBER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ABOVE THIS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ABYSMAL DAWN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ACUMEN NATION', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ACT OF DEFIANCE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('AFTER THE BURIAL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ALL SHALL PERISH', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ALL THAT REMAINS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ALLEGAEON', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ALLUVIAL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ANDROMIDA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ANDY GILLION', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ANDY JAMES', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ANDY TIMMONS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ANGEL VIVALDI', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ANIMALS AS LEADERS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ANUP SASTRY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ANY GIVEN DAY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ARCH ECHO', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ARCH ENEMY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ARCHITECTS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ARSIS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('AS BLOOD TUNS BLACK', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('AS I LAY DYING', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ASKING ALEXANDRIA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('AT THE GATES', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ATREYU', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ATTILA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('AUGUST BURST RED', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('AUSTRIAN DEATH MACHINE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('AVENGED SEVENFOLD', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('BAD WOLVES', 'Heavy metal band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BEARTOOTH', 'Metalcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BEHEMOTH', 'Blackened death metal band from Poland.');
INSERT INTO registro (nombre, descripcion) VALUES ('BENEATH THE SKY', 'Metalcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BERNTH', 'Swedish guitarist known for his solo work and being a member of the band Scar Symmetry.');
INSERT INTO registro (nombre, descripcion) VALUES ('BERRIED ALIVE', 'Progressive metal band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BETRAYING THE MARTYRS', 'Metalcore band from France.');
INSERT INTO registro (nombre, descripcion) VALUES ('BETWEEN THE BURIED AND ME', 'Progressive metal band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BEYOND CREATION', 'Progressive death metal band from Canada.');
INSERT INTO registro (nombre, descripcion) VALUES ('BLACK VEIL BRIDES', 'Glam metal band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BLEED FROM WITHIN', 'Metalcore band from Scotland.');
INSERT INTO registro (nombre, descripcion) VALUES ('BLEED THE SKY', 'Heavy metal band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BLEEDING THROUGH', 'Metalcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BLESSTHEFALL', 'Metalcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BLOOD HAS BEEN SHED', 'Metalcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BLOTTED SCIENCE', 'Technical death metal band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BOYINABAND', 'British YouTuber and musician.');
INSERT INTO registro (nombre, descripcion) VALUES ('BORN OF OSIRIS', 'Progressive metalcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BODYSNATCHER', 'Deathcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BREAKDOWN OF SANITY', 'Metalcore band from Switzerland.');
INSERT INTO registro (nombre, descripcion) VALUES ('BRING ME THE HORIZON', 'Metalcore band from England.');
INSERT INTO registro (nombre, descripcion) VALUES ('BUCKETHEAD', 'American guitarist and multi-instrumentalist known for his virtuosic playing style and eccentric stage presence.');
INSERT INTO registro (nombre, descripcion) VALUES ('BULLET FOR MY VALENTINE', 'Metalcore band from Wales.');
INSERT INTO registro (nombre, descripcion) VALUES ('BURIED IN VERONA', 'Metalcore band from Australia.');
INSERT INTO registro (nombre, descripcion) VALUES ('BURY TOMORROW', 'Metalcore band from England.');
INSERT INTO registro (nombre, descripcion) VALUES ('BURY YOUR DEAD', 'Metalcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('BYZANTINE', 'Groove metal band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('CACOPHONY', 'Neoclassical metal supergroup featuring guitarists Marty Friedman and Jason Becker.');
INSERT INTO registro (nombre, descripcion) VALUES ('CALIBAN', 'Metalcore band from Germany.');
INSERT INTO registro (nombre, descripcion) VALUES ('CALIGULA''S HORSE', 'Progressive metal band from Australia.');
INSERT INTO registro (nombre, descripcion) VALUES ('CANNIBAL CORPSE', 'Death metal band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('CAR BOMB', 'Mathcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('CHELSEA GRIN', 'Deathcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('CHIMAIRA', 'Metalcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('CHON', 'Instrumental progressive rock band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('CHRIS POLAND', 'American guitarist known for his work with Megadeth and Damn the Machine.');
INSERT INTO registro (nombre, descripcion) VALUES ('CIRCUS MAXIMUS', 'Progressive metal band from Norway.');
INSERT INTO registro (nombre, descripcion) VALUES ('CLOUDKICKER', 'Instrumental progressive metal project from Canada.');
INSERT INTO registro (nombre, descripcion) VALUES ('CODE ORANGE', 'Metalcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('CONQUERING DYSTOPIA', 'Instrumental progressive metal supergroup featuring guitarist Jeff Loomis and Keith Merrow.');
INSERT INTO registro (nombre, descripcion) VALUES ('CONVERGE', 'Metalcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('CORONER', 'Thrash metal band from Switzerland.');
INSERT INTO registro (nombre, descripcion) VALUES ('COUNT TO SIX', 'Metalcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('COUNTERPARTS', 'Melodic hardcore band from Canada.');
INSERT INTO registro (nombre, descripcion) VALUES ('CROSSBREED', 'Nu metal band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('CYCLAMEN', 'Progressive metal band from Japan.');
INSERT INTO registro (nombre, descripcion) VALUES ('CYNIC', 'Progressive death metal band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('DANCE GAVIN DANCE', 'Post-hardcore band from America.');
INSERT INTO registro (nombre, descripcion) VALUES ('DARK TRANQUILITY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DARKEST HOUR', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DAVID MAXIM MICIC', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DEAD LETTER CIRCUS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DECAPITED', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DEFTONES', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DEREK SHERINIAN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DEVILDRIVER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DEVIN TOWNSEND', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DEVIN TOWNSEND PROJECT', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DIABLO SWING ORCHESTRA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DIECAST', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DREDG', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('DYING FETUS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('EARTH CRISIS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('EKTOMORF', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ELITIST', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('EMMURE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ENDO', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ERRA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('EVERGREY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('EVETY TIME I DIE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('FALLING IN REVERSE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('FATES WARNING', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('FEAR FACTORY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('FEARED', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('FEED HER TO THE SHARKS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('FELLSILENT', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('FIT FOR A KING', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('FIVE FINGER DEATH PUNCH', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('FOR THE FALLEN DREAMS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('FUNERAL FOR A FRIEND', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('GENERATION AXE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('GHOST BRIGADE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('GLASSJAW', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('GLASSJAW EYEWTKAS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('GOD FORBID', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('GOJIRA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('GOOD TIGER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HACKTIVIST', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HAKEN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HANDS LIKE HOUSES', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HASTE THE DAY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HATEBREED', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HAVOK', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HEATHEN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HEAVEN SHALL BURN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HELLYEAH', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HIMSA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HONOUR CREST', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('HOPESFALL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('I BUILT THE SKY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('I SEE STARS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('I THE BREATHER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ICE NINE KILLS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('IMPENDING DOOM', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('IN FLAMES', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('IN THIS MOMENT', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('INTERVALS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('INTO ETERNITY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('INVENT, ANIMATE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('INVISIONS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('IRON MAIDEN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('IT DIES TODAY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('JAKE HOWSAN LOWE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('JAKUB ZYTECKI', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('JARED DINES', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('JASON BECKER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('JEFF LOOMIS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('JINJER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('JOE STUMP', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('JUDAS PRIEST', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('KARI BAND', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('KARNIVOOL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('KATATURA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('KIKO LOUREIRO', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('KILLSWITCH ENGAGE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('LAMB OF GOD', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('LEE MCKINNEY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('LIKE MOTHS TO FLAMES', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('LEPROUS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('LIQUID TENSION EXPERIMENT', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('LIQUORWORKS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('LIVING SACRIFICE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('LOST SYMPHONY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('LUIS KALIL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MACHINE HEAD', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MAD ESSENCE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MARTY FRIEDMAND', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MASTODON', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MEGADETH', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MEGALODON', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MEMPHIS MAY FIRE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MENDEL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MERROW', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MESHUGGAH', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MESTÍS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('METAL ALLEGIANCE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('METALLICA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MICHAEL ANGELO BATIO', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MICHAEL ROMEO', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MICK GORDON', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MIKE LE ROSSETTI', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MISERY SIGNALS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MISS MAY I', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MNEMIC', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MODERN DAY BABYLON', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MODES OF RANVIER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MONUMENTS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MORS PRINCIPIUM EST', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MOTIONLESS IN WHITE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('MYCHILDREN MYBRIDE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('NE OBLISVISCARIS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('NECROPHAGIST', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('NEVERMORE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('NORMA JEAN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('NORTHLANE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('NUCLEAR POWER TRIO', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('OBEY THE BRAVE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('OCEANO', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('OCTAVISION', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('OF MICE & MEN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('OLA ENGLUND', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('OMNIUM GATHERUM', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('OPETH', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('OUR LAST NIGHT', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('OWANE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('PAGAN''S MIND', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('PANTERA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('PARASITE INC.', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('PARKWAY DRIVE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('PAUL WARDINGHAM', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('PERIPHERY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('PLINI', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('POISON THE WELL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('POKEY LAFARGE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('POLYPHIA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('POMEGRANATE TIGER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('PORCUPINE TREE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('PROTEST THE HERO', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('PSYCOTIC', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('REMEMBERING NEVER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('REVOCATION', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('RINGS OF SATURN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('RIVERS OF NIHIL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ROADRUNNER UNITED', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ROB ZOMBIE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('ROMA IVAKOV', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SATYR', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SCALE THE SUMMIT', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SCAR SYMMETRY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SEA IN THE SKY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SENSES FAIL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SHADOWS FALL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SHAI HULUD', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SHAWN LANE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SHOKRAN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SIKTH', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SILENT PLANET', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SIRENS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SITHU AYE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SKYHARBOR', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SLAYER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SLEEPING WITH SIRENS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SOEN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SOFTEN THE GLARE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SOLUTION .45', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SONS OF ABRAHAM - ALBUM TERMITES IN HIS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SONS OF APOLLO', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('STEVIE T.', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('STICK YOUR GUNS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('STILL REMAINS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('STONE SOUR', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('STORY OF THE YEAR', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('STRAY FROM PATH', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SUICIDE SILENCE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SYLOSIS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('SYMPHONY X', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('TESSERACT', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('TESTAMENT', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('TEXAS IN JULY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('TEXTURES', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THANK YOU SCIENTIST', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE ABSENCE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE ACACIA STRAIN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE AGONY SCENE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE ALGORITHM', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE ARISTOCRATS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE AUTONOMIST', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE BLACK DAHLIA MURDER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE BLED', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE BROWNING', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE CONTORTIONIST', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE DEVIL WEARS PRADA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE DILLINGER ESCAPE PLAN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE FACELESS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE GHOST INSIDE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE HALO EFFECT', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE HAUNTED', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE HELIX NEBULA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE MAGNIFICENT 13', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE OCEAN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE OMNIFIC', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE PLOT IN YOU', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE RED JUMPSUIT APPARATUS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE SORROW', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE USED', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE WORD ALIVE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THE ZENITH PASSAGE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THEIR DOGS WERE ASTRONAUTS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THIS OR THE APOCALYPSE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THRAILKILL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THREAT SIGNAL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THRICE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THROUGH THE EYES OF THE DEAD', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('THY ART IS MURDER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('TIME, THE VALUATOR', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('TIMES OF GRACE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('TINARIWEN', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('TONY MACALPINE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('TOOTHGRINDER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('TOTHEARK', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('TRIVIUM', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('UNDEROATH', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('UNEARTH', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('UNEVEN STRUCTURE', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('UNPROCESSED', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('UPON A BURNING BODY', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('VANNA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('VEIL OF MAYA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('VILDHJARTA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('VITALISM', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('VOLA', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('VOLUMES', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('WAGE WAR', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('WAKING THE CADAVER', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('WALLS OF JERICHO', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('WALTER TROUT', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('WAR OF AGES', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('WE CAME AS ROMANS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('WHILE SHE SLEEPS', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('WHITECHAPEL', 'Descripción del nombre');
INSERT INTO registro (nombre, descripcion) VALUES ('WIDE EYES', 'Banda de metalcore de Carolina del Norte, EE. UU.');
INSERT INTO registro (nombre, descripcion) VALUES ('WIDEK', 'Proyecto en solitario del guitarrista sueco Johan ''Pluto'' Raninen.');
INSERT INTO registro (nombre, descripcion) VALUES ('WILDERUN', 'Banda de metal progresivo de Boston, EE. UU.');
INSERT INTO registro (nombre, descripcion) VALUES ('WINDS OF PLAGUE', 'Banda de deathcore de Los Ángeles, EE. UU.');
INSERT INTO registro (nombre, descripcion) VALUES ('WITHIN THE RUINS', 'Banda de deathcore/progresivo de Massachusetts, EE. UU.');
INSERT INTO registro (nombre, descripcion) VALUES ('YNGWIE J. MALMSTEEN', 'Guitarrista sueco de heavy metal y neo-clásico, conocido por su virtuosismo en la guitarra eléctrica.');

commit;
