#spring:
#  datasource:
#    url: spring.datasource.url=jdbc:mysql://generalbd.clei2awgijc5.us-east-1.rds.amazonaws.com:3306/generalbd
#
#  sql:
#    init:
#      mode: always # you won't do this in prod, I'm just doing this for demo purposes

